<package format="3">
  <name>isaac_policy_runtime</name>
  <version>0.1.0</version>
  <description>Generic ONNX policy runner for ROS 2.</description>
  <maintainer email="you@example.com">Your Name</maintainer>
  <license>BSD-3-Clause</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <exec_depend>rclpy</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
